package pojos;
// Generated Nov 8, 2018 12:31:28 PM by Hibernate Tools 4.3.1



/**
 * DaftarRegistSignin generated by hbm2java
 */
public class DaftarRegistSignin  implements java.io.Serializable {


     private int noIdentitas;
     private String nama;
     private String alamat;
     private String deposit;
     private String sandi;

    public DaftarRegistSignin() {
    }

    public DaftarRegistSignin(int noIdentitas, String nama, String alamat, String deposit, String sandi) {
       this.noIdentitas = noIdentitas;
       this.nama = nama;
       this.alamat = alamat;
       this.deposit = deposit;
       this.sandi = sandi;
    }
   
    public int getNoIdentitas() {
        return this.noIdentitas;
    }
    
    public void setNoIdentitas(int noIdentitas) {
        this.noIdentitas = noIdentitas;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }
    public String getDeposit() {
        return this.deposit;
    }
    
    public void setDeposit(String deposit) {
        this.deposit = deposit;
    }
    public String getSandi() {
        return this.sandi;
    }
    
    public void setSandi(String sandi) {
        this.sandi = sandi;
    }




}


