package pojos;
// Generated Nov 8, 2018 12:31:28 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * FileData generated by hbm2java
 */
public class FileData  implements java.io.Serializable {


     private int jumlahCetakan;
     private Date waktu;
     private String fileCetakan;

    public FileData() {
    }

    public FileData(int jumlahCetakan, Date waktu, String fileCetakan) {
       this.jumlahCetakan = jumlahCetakan;
       this.waktu = waktu;
       this.fileCetakan = fileCetakan;
    }
   
    public int getJumlahCetakan() {
        return this.jumlahCetakan;
    }
    
    public void setJumlahCetakan(int jumlahCetakan) {
        this.jumlahCetakan = jumlahCetakan;
    }
    public Date getWaktu() {
        return this.waktu;
    }
    
    public void setWaktu(Date waktu) {
        this.waktu = waktu;
    }
    public String getFileCetakan() {
        return this.fileCetakan;
    }
    
    public void setFileCetakan(String fileCetakan) {
        this.fileCetakan = fileCetakan;
    }




}


